### ISSUE TITLE
Missing swc

### ISSUE THREAD

**Issue by gerardvde** [myflashlab/LocalNotification-ANE#1]
How do we solve :
import com.myflashlab.air.extensions.localNotifi*;

There is no sourec code or swc

**Comment by myflashlab** [comment]
When embedding the ANE, your IDE should read the AS classes inside. and besides that, the correct import statement is ```import com.myflashlab.air.extensions.localNotifi.*;``` (you missed the dot at the end)

**Comment by myflashlab** [comment]
let us know if you're over this problem? or need more help?

**Comment by gerardvde** [comment]
Problem soleve , needed only the ANE to adress the classes and methods
