### ISSUE TITLE
scheduled notification with message that I can modify it in future 

### ISSUE THREAD

**Issue by prof3d** [myflashlab/LocalNotification-ANE#10]
Hello..
about LocalNotification-ANE
How can I make a scheduled notification with message that I can modify it in future using data in xml file.
Example:
The script is your demo project  with no change I don’t need to write it again here except this 3 lines to explain my question:
```actionscript
setting.title = "the title";
setting.message = "the message";
setting.time = new Date().getTime() + 259200000; // means 3 days from now
```
after 3 days I get the notification even app is closed ok. But with old title and message.
This what I need:
```actionscript
setting.title = (string variable that I can modify it after 3 days by URLLoader);
setting.message = (string variable that I can modify it after 3 days by URLLoader);
setting.time = new Date().getTime() + 259200000; // means 3 days from now
```

**Comment by myflashlab** [comment]
well, you may [unset](http://myflashlab.github.io/asdoc/com/myflashlab/air/extensions/localNotifi/Notification.html#unset()) the previously set notification and re scheduled one with new information.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
