### ISSUE TITLE
Request: Notification Time interval 

### ISSUE THREAD

**Issue by Samuramu** [myflashlab/LocalNotification-ANE#3]
Hi, 
On a free ANE I used before, I used:
 NotificationTimeInterval.DAY_CALENDAR_UNIT 
to run a daily notification.
This was massively useful.
Was wondering if you could incorporate this into your otherwise useful ANE.
Thanks,

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
