### ISSUE TITLE
No Icon badge support

### ISSUE THREAD

**Issue by aram-ahak** [myflashlab/LocalNotification-ANE#6]
## Problem Description ##
There is no support for icon counter badges, and this makes the whole local notification ANE quite useless.

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
