### ISSUE TITLE
How do I use custom icon?

### ISSUE THREAD

**Issue by arcreature7** [myflashlab/LocalNotification-ANE#7]
I have a question about value of **NotificationAndroidSettings**.
(I sent an email to club support, but I have no reply.)
The status bar at the top of Android requires a mono color icon.
However, **NotificationAndroidSettings** does not have properties like NotificationCompat.Builder.setSmallIcon().
How do I use custom icon?

## Environment ##
* Android API Version: localNotification-V1.0.1
* AIR SDK Version: 28

## Problem Description ##
Can't use custom icon.

**Comment by myflashlab** [comment]
Custom icons are not yet supported with the current version. We have this in our to-do list though and we'll add it in our next release. Thanks. I have marked this ticket.

**Comment by Dimonte** [comment]
Any news on the issue?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
