### ISSUE TITLE
Oreo 8.0

### ISSUE THREAD

**Issue by ikuprin** [myflashlab/LocalNotification-ANE#8]
Looks like not works any Oreo 8.0 device.

**Comment by myflashlab** [comment]
We don't see any problem with Android 8! It's all working as expected. Please provide more information about the problem you are experiencing.

**Comment by ikuprin** [comment]
Hum. 
Some research show me that in your example targetSdkVersion="23" - works as expected. targetSdkVersion="25" - also works as expected. But targetSdkVersion="26" - not works...

**Comment by myflashlab** [comment]
Great, thanks for bringing this up. You're right. On Android 8+ notifications won't show if you are compiling with SDK 26+ unless you are introducing [NotificationChannels](https://developer.android.com/training/notify-user/channels)

We have now updated the ANE to support this feature. Please have a test with the updated **demo** ANE before we release it. [localNotification.ane.zip](https://github.com/myflashlab/LocalNotification-ANE/files/2001656/localNotification.ane.zip)

Follow the below instruction to create channels.

```actionscript
/*
On Android, if you have set targetSdkVersion to 26 or higher, notifications won't work unless they
have a channel. To do that, simply create one or more channels like below and whenever you want to
construct a new notification, simply pass the channel id to the NotificationAndroidSettings instance.

NOTICE: Create channels AFTER you have initialized the ANE
*/
		
// create a new channel with a unique id
var channel:NotificationChannel = new NotificationChannel("myChannelId", "channel name");
		
// set the channel properties
channel.description = "channel description";
		
// finally register the channel.
if(Notification.OS == Notification.ANDROID) Notification.registerChannel(channel);
```
Later, when you want to construct a new notification, when you are setting the Android settings in ```NotificationAndroidSettings``` class, set the channel id you wish.
```actionscript
setting.channelId = "myChannelId";
```

This is tested and works fine on our devices. Let's hear your feedback now :)

P.S  NotificationChannels have many more settings. We will be adding them in future versions of this ANE.

**Comment by myflashlab** [comment]
V2.0.0 is now released.

**Comment by ikuprin** [comment]
All works as expected! Thank you.
Waiting for release version.
